### ISSUE TITLE
Dowload curl images from local repo

### ISSUE THREAD

**Issue by sergioatom** [pingidentity/helm-charts#10]
https://github.com/pingidentity/helm-charts/blob/593e106b9da52d89a8a3c3fe7db4c4c6f164f174/charts/ping-devops/templates/pingfederate-engine/deployment.yaml#L15

I'd like to be able to override this image path to point to our local repo as the cluster has no internet access. 

Thanks

**Comment by tsigle** [comment]
Thanks for that info.  It's a fair ask.  Will take a look at this.

**Comment by tsigle** [comment]
Hey Sergio,

Proposing the change I just checked in.  Amounts to:

  ```
global:  
  ############################################################
  # External Images
  #
  # Provides ability to use external images for various purposes
  # such as using curl.
  ############################################################
  externalImage:
    curl: curlimages/curl:latest
```

note that, you can also override this by product with something like:

```
pingfederate-engine:
  externalImage:
    curl: myrepo/curl-image:1.2
```

And this is used in the helm chart for pingfederate-engine:

```
    spec:
      initContainers:
      - name: init
        image: {{ $v.externalImage.curl }}
```
