### ISSUE TITLE
Update default serviceAccount in workload related to Issue 95

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#112]
When Issue #95 was resolved, the vault serviceAccountName was still pulling from:

```
  vault:
    hashicorp:
      serviceAccountName: vault-auth
```

but that default was removed from the default `values.yaml`.  The new proper location is:

```
  vault:
    hashicorp:
      annotations:
        serviceAccountName: vault-auth
```

workload template should use the new location:

```
  serviceAccountName: {{ $v.vault.hashicorp.annotations.serviceAccountName }}
```
