### ISSUE TITLE
Support Annotations at Workload Level

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/helm-charts#116]
Right now annotations are at the top level (global/product) in values.yaml and this adds them to all resources under that product. This may be misleading. We should support annotations at the workload level. For workloads, annotations should be added at `.spec.template.metadata` as this is where most 3rd party operators look (examples: vault, telegraf-operator). 

```
pingfederate-engine:
  workload:
    annotations:
      telegraf.influxdata.com/class: app
```
would lead to:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: samir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pingfederate-engine
    helm.sh/chart: ping-devops-0.5.1
  name: samir-pingfederate-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: samir
      app.kubernetes.io/name: pingfederate-engine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        telegraf.influxdata.com/class: app
```
