### ISSUE TITLE
Workload helm template not honoring persistentvolume.enabled=false

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#119]
The default for persistentvolume.enabled in the values.yaml is set to:

```
global:
  workload:
    statefulSet:
      persistentvolume:
        enabled: true
```

However if the deployer sets this to `false` when the merge happens, it will merge `true` and `false` ==> `true`.
