### ISSUE TITLE
Unable to mount secretVolume and configMapVolumes simultaneously

### ISSUE THREAD

**Issue by ilhaan** [pingidentity/helm-charts#126]
I have the following in my custom `values.yaml` for pingfederate-admin: 

```
pingfederate-admin:
  enabled: true

  secretVolumes:
    pingfederate-license:
      items:
        license: /opt/in/instance/server/default/conf/pingfederate.lic

  configMapVolumes:
    pingfederate-props:
      items:
        pf-props: /opt/in/etc/pingfederate.properties 
```

I created the secret and  configmap using the following kubectl commands: 

```
kubectl create secret generic pingfederate-license --from-file=license=<path-to-license-file>
kubectl create configmap pingfederate-props --from-file=pf-props=<path-to-properties-file>
```

However, the helm chart seems to only use the `configMapVolume` if both volumes are defined as shown in my `values.yaml` config. When I remove the `configMapVolumes` block, and re-run helm, the license mount shows up. 

I even tried switching the order these are defined in `values.yaml` and saw the same behavior in chart versions 0.5.1 and 0.5.3. 

Let me know if I am doing something wrong here and how I can fix this.
