### ISSUE TITLE
Add clusterServiceName to product services with clusters

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#155]
There is a situation with PingFederate when deployed across k8s clusters when the pingfederate-admin is in only one k8s cluster.  This ends up having other k8s clusters without an admin and the naming for the cluster-service is hard to automatically set, based on the name of the product (i.e. pingfederate-admin -vs- pingfederate-engine).  In some customers, they want to provide their own clusterServiceName.

Request is to add an additional setting in the product.services structure to specify a clusterServiceName if a custom one is requested.

Examples for both pingfederate-admin and pingfederate-engine
```
pingfederate-admin:
  services:
    clusterServiceName: pingfederate-cluster

pingfederate-engine:
  services:
    clusterServiceName: pingfederate-cluster
```

In this example it's intentional that the cluster service name be the same between both the admin and the engine.  By default, this would be the only one set.  If clusterServiceName isn't set, then it would default to: {product.name}-cluster.

And in all cases, the helm release would be appended/prepended as specified by the `addReleaseNameToResource` setting.
