### ISSUE TITLE
Reevaluate Lifecycle probes

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/helm-charts#171]
At minimum, PD's lifecycle probs are a bit off. Liveness and readiness are using /opt/liveness.sh, but readiness should be using /opt/readiness.sh.

Also, it looks like we only support liveness and readiness right now, we should add startup also. 

here's an example of what I believe PD's lifecycle probes should look like: 

```
  probes:
    liveness:
      command: /opt/liveness.sh
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readiness:
      command: /opt/readiness.sh
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 2
      failureThreshold: 2
    startupProbe:
      command: /opt/liveness.sh
      failureThreshold: 90
      periodSeconds: 10
```

**Comment by tsigle** [comment]
Adding startupProblem as well as re-organizing how the probes are defined, allowing the deployer to use standard k8s probe definitions out of the box. 

1. Moving the probes section under global.container
2. Changing names: (liveness --> livenessProbe, readiness --> readinessProbe)
3. Adding startupProbe

The new default looks like:

```
    ############################################################
    # Probes
    #
    # Probes have a number of fields that you can use to more precisely control the
    # behavior of liveness and readiness checks.
    #
    # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
    ############################################################
    probes:
      livenessProbe:
        exec:
          command:
            - /opt/liveness.sh
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      readinessProbe:
        exec:
          command:
            - /opt/readiness.sh
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      startupProbe:
        exec:
          command:
            - /opt/liveness.sh
        periodSeconds: 10
        failureThreshold: 90
```

Note: this is a breaking change if anyone has overriding probes in their own values file.  The fix is simply move their definition of their probes to live under global.container or the (productName).container, as well as adding "Probe" to the definition.

Note: Eventually, it is recommended to create an /opt/startup.sh (or some similar name) in the images, so that can be the standard script called instead of /opt/liveness.sh.  Initially, it can be similar to the standard /opt/readiness.sh, which simply calls liveness.sh.
