### ISSUE TITLE
Invalid ingress resources on Kubernetes clusters > 1.18

### ISSUE THREAD

**Issue by jjustinic** [pingidentity/helm-charts#175]
With the release of `0.6.7`, the chart fails install / upgrade a release with ingress enabled on a cluster running a Kubernetes version greater than `1.18`. While this version of the chart added logic to use `apiVersion: networking.k8s.io/v1` instead of `apiVersion: networking.k8s.io/v1beta1` on newer versions of Kubernetes, it does not have any logic to handle the updates to the contract between `v1beta1` and `v1` of Ingress resources.

The primary changes between `v1beta1` and `v1` are:

- `spec.backend` -> `spec.defaultBackend`
- `serviceName` -> `service.name`
- `servicePort` -> `service.port.name` (for string values)
- `servicePort` -> `service.port.number` (for numeric values)
- `pathType` no longer has a default value in v1; `Exact`, `Prefix`, or `ImplementationSpecific` must be specified for each.

Therefore, what is generated as:

```
spec:
  rules:
    - http:
         paths:
           - path: /
             backend:
               serviceName: pingfederate-engine
               servicePort: 9031
```

Needs to look closer to this on versions `> 1.18`:

```
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingfederate-engine
                port:
                  number: 9031
```

**Comment by jjustinic** [comment]
The exact error received when attempting to run the upgrade is:
```
Error: UPGRADE FAILED: error validating "": error validating data: [
  ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend,
  ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend
]
```

**Comment by tsigle** [comment]
Thanks @jjustinic , looking into this.

**Comment by tsigle** [comment]
As @jjustinic points out (Thanks @jjustinic)  the syntax has changed.  Making a mod in the ingress template to emit different backend details depending on KubeVersion and ultimate use of (v1beta1 -vs- v1).  Template section will be changed to:

```
            backend:
{{- if semverCompare ">1.18" $top.Capabilities.KubeVersion.Version }}
              serviceName: {{ $fullName }}
              servicePort: {{ (index $v.services .backend.serviceName).servicePort }}
{{- else }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ (index $v.services .backend.serviceName).servicePort }}
{{- end }}
```

I hope to get this updated, tested and released later today.
