### ISSUE TITLE
Change default envs for pingauthorize/pingauthorizepap

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#194]
The current envs for pingauthroize in the values.yaml file are:

```
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: paz-pap-integration/pingauthorize
    SERVER_PROFILE_PARENT: PAZ
    SERVER_PROFILE_PAZ_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PAZ_PATH: baseline/pingauthorize
```

Just a side note here, the `baseline/pingauthorize` PATH includes a connection to pingdirectory, which will cause this to fail (pingauthorize https will return a 503).

If someone wants to override these, they need to be sure to uset/override the `SERVER_PROFILE_PARENT` variable, so the parent profiles aren't brought in.

The better default values.yaml should probably be:

```
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingauthorize
```

For pingauthorizepap, it should have a default SERVER_PROFILE variables as empty, as no SERVER_PROFILE is needed by default.
