### ISSUE TITLE
Error starting pingfederate-engine init container on openshift if pod does not have anyuid (uid/gid  0) scc rights

### ISSUE THREAD

**Issue by gsustek** [pingidentity/helm-charts#196]
In _workload.tpl on line 266 helm-chart version 0.7.2 there is hardcoded InitContainer resources values. 

`{{- define "pinglib.workload.init.default.resources" -}}
resources:
  limits:
    cpu: 0
    memory: 128Mi
  requests:
    cpu: 0
    memory: 64Mi
{{- end -}}`

which on openshift cause a non starting pf-engine init container with following error:

Pod "team-cpc2-pingfederate-pingfederate-engine-6c56997d5f-4gkxp" is
invalid: spec.initContainers[0].resources.requests: Invalid value: "1m":
must be less than or equal to cpu limit

Porposal:
- either you put "1m" or make those values configurable from values.yaml 

Regards,
Goran.

**Comment by tsigle** [comment]
Hi Goran,

Good call on this issue.  Yes, at a minimum, we can set the request limit to 1m as the default.

I like your suggestion to make it configurable in the values.yaml.  We do use these request limits on a couple of initiContainers (wait-for and private-cert-creation).  I'm thinking of adding:

```
global:
  workload:
    initContainer:
      resources:
        limits:
          cpu: 1m
          memory: 128Mi
        requests:
          cpu: 500m
          memory: 64Mi
```

Of course, if you put these on a product, rather than global, then it could technically be overridden on a product by product basis, but I wouldn't expect that.  These are primarily used for the internal containers, but should the implementer override the externalImage, then I can see that they'd want to provide their own settings.  With respect to tying it to the image, the other thought might be to adde it to the externalImage values.  Such as:

```
global:
  externalImage:
  pingtoolkit:
    image: pingidentity/pingtoolkit:2107
    resources:
        limits:
          cpu: 1m
          memory: 128Mi
        requests:
          cpu: 500m
          memory: 64Mi
```

If we did it this way, it would basically allow for full control of resources as well as anything related to the initContainer.

Interested in any thoughts you might have on this.
