### ISSUE TITLE
Fix incorrect default ldap-sdk-tools probe exec commands

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#209]
Error in the ldap-sdk-tools probe exec commands values.yaml file.

```
ldap-sdk-tools:
...
    probes:
      livenessProbe:
        exec:
          command: echo
      readinessProbe:
        exec:
          command: echo
```

Should be an array

```
ldap-sdk-tools:
...
    probes:
      livenessProbe:
        exec:
          command: 
            - echo
      readinessProbe:
        exec:
          command:
            - echo
```
