### ISSUE TITLE
Remove default SERVER_PROFILE info in values.yaml

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#213]
To allow for easy deployment of the charts, we initially, and still do, provide default SERVER_PROFILE_... variables in the values.yaml to some of the example profiles in Ping Identity server profile github repos.  An example from pingfederate-admin:

```
pingfederate-admin:
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate
```

If possible, these defaults should probably be removed, requiring any designation of SERVER_PROFILES be provided to the deployment, as an example the [pingfederate.yaml example](https://helm.pingidentity.com/examples/pingfederate.yaml).

Additionally, it is very important that the SERVER_PROFILE_BRANCH=(git branch/tag) be added, so a deployment with a specific docker tag (i.e. 2108) is running with an expected SERVER_PROFILE branch/tag (i.e. 2108).
