### ISSUE TITLE
Update default security context group id to root (0)

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#217]
With recent updates to the default group id to root (0) in the 2109 version of the Ping Identity images, the default security context group id will be changed from 9999 to 0.

```
global:
  workload:
    securityContext:
      fsGroup: 0
      runAsUser: 9031
      runAsGroup: 0
```
