### ISSUE TITLE
Add support for HPA scaling behaviour

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/helm-charts#223]
PF pods may scale up upon initial deploy because of high CPU util on startup. 
We may be able to prevent this false scale up by leveraging https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior: 
```
behavior:
  scaleDown:
    stabilizationWindowSeconds: 300
    policies:
    - type: Percent
      value: 100
      periodSeconds: 15
  scaleUp:
    stabilizationWindowSeconds: 0
    policies:
    - type: Percent
      value: 100
      periodSeconds: 15
    - type: Pods
      value: 4
      periodSeconds: 15
    selectPolicy: Max
```
