### ISSUE TITLE
privateCert.additionalHosts is not honored

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/helm-charts#234]
With values.yaml like: 

```
pingaccess-admin:
  enabled: true
  privateCert:
    generate: true
    additionalHosts: 
      - myhost-pingaccess-admin.usa.ping-multi-cluster.com
      - myhost-pingaccess-admin
```

The cert is created with only the main domain. Alternate names is not populated according to additionalHosts. 

Thinking this may be due to code somewhere here: https://github.com/pingidentity/helm-charts/blob/master/charts/ping-devops/templates/pinglib/_yamlSnippets.tpl#L58
but, not confirmed.
