### ISSUE TITLE
how to work with topologySpreadConstraints

### ISSUE THREAD

**Issue by eikster-dk** [pingidentity/helm-charts#272]
Hello 

I want some guidance in settings the `topologySpreadConstraints` correctly for Directory and ping federate. Currently it requires you to set the match selectors manually and this requires you to hardcode the matchSelectors in the values file

Is there a way to get the matchLabels dynamically set to the same as the resulting workload labels? 

example:
```
global:
  workload:
    topologySpreadConstraints:
      - topologyKey: topology.kubernetes.io/zone
        maxSkew: 3
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: xx
            app.kubernetes.io/instance: yyy
pingfederate-admin:
  enabled: true
pingfederate-engine:
  clustering:
    autoscaling:
      enabled: true
      minReplicas: 3
  enabled: true
..........
```
