### ISSUE TITLE
Pingfederate StatefulSet persistentvolume creation

### ISSUE THREAD

**Issue by KiranmaiKalla** [pingidentity/helm-charts#274]
We are trying to attach existing persistentvolumeClaim to PF-admin pod, but it while deploying by default it is creating the pvc again. Is there a way to use existing pvc.

Below is our config, please help.

`  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        enabled: true
        volumes:
          out-dir:
            mountPath: /opt/out
            persistentVolumeClaim:
              claimName: pingfederate-managed-csi-pvc-1    
`

**Comment by henryrecker-pingidentity** [comment]
You may be able to use `selector` with labels to pick your existing volume. Just add the corresponding labels to the volume you want to use. You'll need to ensure you have separate volumes for any separate pods.

```
pingfederate-admin:
  enabled: true
  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        enabled: true
        volumes:
          out-dir:
            mountPath: /opt/out
            persistentVolumeClaim:
              selector:
                matchLabels:
                  foo: foo
                  bar: bar
```

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#persistentvolumeclaimspec-v1-core
