### ISSUE TITLE
Run Ping containers with non-root security context

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/helm-charts#28]
Currently working through a deployment into a controlled environment that performs hardened image scans prior to deployment.  We have to add the following to the deployment/statefulset manifests to get it to work:

```
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
```
Can this please be added in the core chart?

**Comment by tsigle** [comment]
Adding the ability for a deployer to add a securityContext to the containers.  Currently, there are warning messages in the images when an outside-in pattern is used (i.e. securityContext is set).  Also, many of the default ports require privileged access, so care should be taken along with testing to ensure the containers start up fine.  Additional, one should not change the security context when doing and upgrade or using a PCV from a previous deployment.

An example securityContext that can be used might look like:

```
global:
  container:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 100
```

By default, the values.yaml in the chart will set the securityContext to empty:

```
global:
  container:
    securityContext: {}
```
