### ISSUE TITLE
ingress.class deprecated - Missing support for ingressClassName

### ISSUE THREAD

**Issue by zerowebcorp** [pingidentity/helm-charts#282]
An installation using the older helm chart values aren't working on Kubernetes 1.25 or above ( tested on 1.25.6 )

```
pingfederate-admin:
  enabled: true
  image:
    tag: 2307-11.2.7
  ingress:
    enabled: true
    hosts:
      - host: myhostname.com
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
    addReleaseNameToHost: none
    defaultDomain: "hostname.com"
    defaultTlsSecret: my-wildcard-ssl
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx"
```

Kubernetes/Nginx dropped support for `kubernetes.io/ingress.class: "nginx"` as far as I can see. 

https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

To make the ingress work, I had to add this manually outside of the helm chart.

```
spec:
  ingressClassName: nginx
```

Can you add support for `ingressClassName` in the helm chart? 

Upon looking at the ingress template - charts/ping-devops/templates/pinglib/_ingress.tpl
