### ISSUE TITLE
Persistent Volume is being created even through enabled=false is set.

### ISSUE THREAD

**Issue by zerowebcorp** [pingidentity/helm-charts#285]
When deploying PingFederate as StatefulSet workload, the PVC is being created even though the setting `persistentvolume` is set to `false` at the `global` level. Is this expected and should we override this at the `pingfederate-engine` level or is this a bug?

values.yaml
```
global:
  workload:
    type: "StatefulSet"
  statefulSet:
    persistentvolume:
      enabled: false
pingfederate-engine:
  container:
    replicaCount: 1
  enabled: true
```

When this config is applied, the pod is created with a PVC attached to it with the name

![image](https://github.com/pingidentity/helm-charts/assets/914305/ddebaf95-bbdf-4aa0-bff0-80386bbaf836)

Volume is not being created if `workload.type` is changed to `Deployment` 

Expectation: I was expecting that by setting the `persistentvolume.enabled=false` no PVC should be created for this pod.

**Comment by zerowebcorp** [comment]
Nevermind, The issue is due to indentation. 

```
global:
  workload:
    type: "StatefulSet"
    statefulSet:
      persistentvolume:
        enabled: false
```
