### ISSUE TITLE
Improved Default Naming on Global vars

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/helm-charts#56]
The current output of the default ports _looks_ redundant:
```
apiVersion: v1
data:
  PA_ENGINE_ACME_PRIVATE_PORT: "8080"
  PA_ENGINE_ADMIN_PRIVATE_PORT: "9000"
  PA_ENGINE_ENGINE_PRIVATE_PORT: "3000"
  PA_ENGINE_PRIVATE_HOSTNAME: pingaccess
  PD_ENGINE_HTTPS_PRIVATE_PORT: "443"
  PD_ENGINE_LDAP_PRIVATE_PORT: "389"
  PD_ENGINE_LDAPS_PRIVATE_PORT: "636"
  PD_ENGINE_PRIVATE_HOSTNAME: pingdirectory
  PDG_ENGINE_HTTPS_PRIVATE_PORT: "443"
  PDG_ENGINE_PRIVATE_HOSTNAME: pingdatagovernance
  PF_ADMIN_ADMIN_PRIVATE_PORT: "9999"
  PF_ADMIN_PRIVATE_HOSTNAME: pingfederate-admin
  PF_ENGINE_ENGINE_PRIVATE_PORT: "9031"
  PF_ENGINE_PRIVATE_HOSTNAME: pingfederate-engine
kind: ConfigMap
metadata:
  name: global-env-vars
```

this is reflective of the naming structure:
<product>_<purpose>_<port_name>_<pub/private>_PORT

Since this naming structure provides flexibility of renaming ports the default portnames should be changed to produce more comprehensible variable names. 
like PingDirectory vars. 

**requested enhancement:**
change PF admin and engine port names to "https"

this should give better names that could be more appropriately used as convention:
```
  PF_ADMIN_HTTPS_PRIVATE_PORT: "9999"
  PF_ADMIN_HTTPS_PUBLIC_PORT: "443"
```
