### ISSUE TITLE
When creating configMapRef's, take into account the proper release name to include

### ISSUE THREAD

**Issue by tsigle** [pingidentity/helm-charts#62]
Currently, when a configMapRef is created in the workload it always assuemes a name with a preceding `Release.Name`.

```
        envFrom:
        - configMapRef:
            name: {{ $top.Release.Name }}-global-env-vars
            optional: true
        - configMapRef:
            name: {{ $top.Release.Name }}-env-vars
            optional: true
```

The include should be used to mimic the name that is used when naming the configMapRef and honor the setting of the `addReleaseNameToResources` value.

```
name: {{ include "pinglib.fullname" . }}-env-vars
```
