### ISSUE TITLE
Affinity support

### ISSUE THREAD

**Issue by sergioatom** [pingidentity/helm-charts#78]
Hi. Would you be able to add support for affinity for the engines? We'd like to avoid the pods clustering within the same node and spread them instead for further resilience.

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

Thanks

**Comment by tsigle** [comment]
Thanks for adding this request.  It has been something on our roadmap, and will add that to this next 0.4.2 release.  It will most likely add an affinity structure, defined by your values.yaml:

```
      affinity: {{ toYaml $v.container.affinity | nindent 8 }}
```

However defaulted (or simply recommended) to something like (pingdirectory as an example):

```
      affinity:
        podAntiAffinity:
          # Deploy each pod to different node (REQUIRED)
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - pingdirectory
            topologyKey: "kubernetes.io/hostname"
          # Deploy each pod to different AZ (OPTIONAL)
          # Add a soft requirement for each PD pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - pingdirectory
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
```
